apiVersion: v1
kind: Namespace
metadata:
  name: fastapi-starter
  labels:
    app.kubernetes.io/name: fastapi-starter
    app.kubernetes.io/instance: fastapi-starter
    app.kubernetes.io/part-of: fastapi-starter
